nginx:
  image: nginx
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/log:/var/log/nginx
    - ./app:/root/app
    - /tmp:/tmp
  ports:
    - "80:80"
mongo:
  image: mongo
uwsgi-flask:
  build: uwsgi-flask
  links:
    - mongo:mongo
  volumes:
    - ./app:/root/app
    - /tmp:/tmp
  environment:
    - MAIL_SERVER
    - MAIL_USERNAME
    - MAIL_PASSWORD