nginx:
  image: nginx
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/log:/var/log/nginx
    - ./certs/.key:/etc/nginx/server.key
    - ./certs/.crt:/etc/nginx/server.crt
    - ./app:/root/app
    - /tmp:/tmp
  ports:
    - "80:80"
    - "443:443"
postfix:
  image: catatnight/postfix
  volumes:
    - ./certs:/etc/postfix/certs
  ports:
    - "587:587"
  environment:
    maildomain: mail.example.com
    smtp_user: "user:pwd"
mongo:
  image: mongo
uwsgi-flask:
  build: uwsgi-flask
  links:
    - postfix:postfix
    - mongo:mongo
  volumes:
    - ./app:/root/app
    - /tmp:/tmp